[package]
name = "ctflgrdiff"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.0", features = [ "derive"] }
crossterm = "^0.25"
ctflgrdifflib = { path = "../difflib" }
tui = "^0.19"
